### ISSUE TITLE
Execute custom validation only if there are no built-in errors on field

### ISSUE THREAD

**Issue by devistar** [semisleep/simple-vue-validator#35]
My custom method validation (async) prevents built-in rules from being tested. It would be nice if the custom validation rule would be done only if the built-in rules are validated.

I tried this without success.

```javascript
"bailleur.nom": {
      debounce: 800,
      validator: function(value) {
        return this.$RulesFor(value)
          .required()
          .maxLength(100)
          .custom(() => {
            if (!this.validation.hasError("bailleur.nom")) {
              let filter = [
                { key: "id_ne", value: this.bailleur.id },
                { key: "nom", value: value }
              ];
              return this.isBailleurNomUnique(filter)
                .then(() => {
                  return "Le bailleur existe déjà.";
                })
                .catch(() => {});
            }
          });
      }
    },
```

**Comment by semisleep** [comment]
I'm sorry that it doesn't work for you in this case. 


From the perspective of validator, it will validate all rules at once, so that the full validation result can be accessed in `this.validation` map, that's why it won't return until all the rules are executed. And indeed,  the async custom rule here will block other built-in rules. 


I don't see any easy work around without modifying the source code in many places, which will probably bring other issues, and I don't have the time to perform a throughout testing :(

Might be you can refactor you code a bit, so that it can get pass your test? For example, during the test, the `this.isBailleurNomUnique` method can be changed to simply return mock result instead of hitting the server?

And of course, you are welcome to contribute to this project by updating the source code to fix this :)

**Comment by devistar** [comment]
I have troubles with custom validation.
1) Built-in methods are not validated.
2) When I call $validate method it returns promise with undefined state. Even if there are not validation errors, it doesn't enter in then scope. Same thing happens if I call an api or I use mockup setTimeout.
If I remove custom validation everything works great.
I would like to contribute but I don't have good level in javascript and I have difficulty to understand your code.
I lose a lot of time on this. :/

**Comment by semisleep** [comment]
Both custom validation and async validation should work, I use them a lot in my personal projects, and also the doc-site have working examples: http://simple-vue-validator.maijin.info/#async_validation

Is it possible for you to create a jsfiddle example that can reproduce the problem, so that I can perform further inspection? Thanks

**Comment by devistar** [comment]
Ok I will do this. How can I add plugin to use it in jsfiddle ?
Thank you.

**Comment by semisleep** [comment]
Hmm... You are right, there's no way to use vue plugin in jsfiddle. Might be you can post some code snippets here?

**Comment by semisleep** [comment]
Or it's better if you can package your codes as a github / gitlab project?

**Comment by devistar** [comment]
I forked your repo and I added UMD build. I also updated doc.
Then it will be possible to use the plugin directly inside a web page.
```html
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
<script src="https://unpkg.com/simple-vue-validator/dist/umd-plugin.js"></script>
```
I tested with raw git and jsfiddle and It works.
https://jsfiddle.net/suybh3co/3/

I will update jsfiddle later for my issue.

**Comment by semisleep** [comment]
Nice! Please let me know when the jsfiddle is updated, thanks.

**Comment by devistar** [comment]
See the bug: 
https://jsfiddle.net/suybh3co/15/

**Comment by semisleep** [comment]
@devistar I check the jsfiddle, the way you create a promise is not correct:
```
          return new Promise(function(resolve) {
              setTimeout(function() {
                if (value === "devistar") {
                  resolve();
                }            	
              }, 500);
            }).then(function() {
              return "Already taken";
            });
```
Note that in the setTimeout callback, you only call resolve when the value is `devistar`, that means for any other values, the promise will never be resolved, and that's why you got a promise with undefined state.

I change the code as below, and it works:
```
          return new Promise(function(resolve) {
              setTimeout(function() {
                if (value === "devistar") {
                    resolve("Already taken");
                }            	
                resolve();
              }, 500);
            })
```

**Comment by devistar** [comment]
Ok thank you for helping me.

**Comment by cesarpastorini** [comment]
@devistar Got same problem like your original issue here. Solved with this:

```javascript
"foo": {
    debounce: 800,
    validator(value) {
        let v = Validator.value(value)
            .required()
            .minLength(5)
            .maxLength(100)

        if (v._messages.length === 0 && !Validator.isEmpty(value)) {
            return Validator.custom(() => {
                this.spinloader = true

                return axios.get('URL/?foo='+this.foo)
                    .then((res) => {
                        this.spinloader = false
                        if (!res.data.success) {
                            return res.data.error.msg.somewhere
                        }
                    })
                    .catch((err) => {
                        this.spinloader = false
                        return 'Error in contacting server'
                    })
            })
        }

        return v 
    }
}
```
Yes, it's a hack. The key to this is the `_messages` property of the validator.
