### ISSUE TITLE
[Feature Request] Single Field Validation

### ISSUE THREAD

**Issue by brwr** [semisleep/simple-vue-validator#7]
I was looking for a way to validate a single field earlier today and couldn't find anything documented. It looks like all of the bound validator functions are stored in an array and can't be requested by field name.

I think having the ability to validate a single field would be a great feature and I'm happy to do what i can to implement it if you're busy.

P.S. Amazing project! Finding a good validation library for Vue 2.0 has been rough, but I'm really enjoying `simple-vue-validator`.

**Comment by semisleep** [comment]
Right, for now the `$validate()` method performs a full validation, I think we would add the field name as parameter to this method to support validating specific fields, I can make that change today as it should be quite easy.
BTW, I'm curious about the incentive of single field validation, because it looks like in most cases this can be implemented by added an extra dependency field for validator (much like cross field validation), for example:
```
'name, otherCondition': function(name, otherCondition) {
  if (otherCondition) {
    return Validator.value(name).required();
  }
}
```
Any change to `otherCondition` can then trigger single field validation for `name`.

And it's really great to hear that you enjoy this library, I also spent quite some time trying different vue 2.0 validation libs,  but fail to find one suitable for my project, so I ended up writing one.

**Comment by semisleep** [comment]
`$validate()` method is now updated to accept either a single field name or an array of field names, I've published the newest code to NPM. 
I don't have any real world usage for this, so would you please help to test if the new signature is working properly?

Thanks!

**Comment by brwr** [comment]
My use case is validating a field on `blur`. Maybe adding an extra dependency like you mentioned above will handle that?

I'll upgrade now and do some testing.

**Comment by brwr** [comment]
The single-field validation is working great! Thanks for getting it in so quickly.
